#!/bin/bash

# apt-get install valac-0.18 gtk-doc-tools

# Gee:    apt-get install libgee-dev,          valac --pkg=gee-1.0
# Soup:   apt-get install libsoup-2.4-dev,     valac --pkg=libsoup-2.4
# Json:   apt-get install libjson-glib-dev,    valac --pkg=json-glib-1.0
# Sqlite: apt-get install libsqlite3-dev,      valac --pkg=sqlite3
# Posix:                                       valac --pkg=posix --Xcc=-D"_GNU_SOURCE"
# Gtk:    apt-get install libgtk-3-dev,        valac --pkg=gtk+-3.0
# Daemon: apt-get install libdaemon-dev,       valac --pkg=libdaemon
# Gst:    apt-get install libgstreamer1.0-dev, valac --pkg=gstreamer-1.0

# gstreamer1.0-pulseaudio, gstreamer1.0-plugins-base

compile()
{
    find "${@:2}" \( -name '*.gs' -o -name '*.vala' \) -print0 | xargs -r0 \
    valac \
        --basedir=src \
        --output=$1 \
        --directory=bin \
        \
        --thread \
        --target-glib=2.32 \
        --Xcc=-w \
        --debug \
        \
        --pkg=libsoup-2.4 \
        --pkg=gee-1.0 \
        --pkg=json-glib-1.0 \
        --pkg=posix --Xcc=-D"_GNU_SOURCE" \
        --pkg=sqlite3 \
        --pkg=gtk+-3.0 \
        --pkg=libdaemon \
        --pkg=gstreamer-1.0

        #--enable-deprecated \
}

ccode()
{
    rm -rf c
    find "${@}" \( -name '*.gs' -o -name '*.vala' \) -print0 | xargs -r0 \
    valac \
        --ccode \
        --basedir=src \
        --directory=c \
        --header=c/khovsgol.h \
        \
        --thread \
        --Xcc=-w \
        \
        --pkg=libsoup-2.4 \
        --pkg=gee-1.0 \
        --pkg=json-glib-1.0 \
        --pkg=posix --Xcc=-D"_GNU_SOURCE" \
        --pkg=sqlite3 \
        --pkg=gtk+-3.0 \
        --pkg=libdaemon
}

doc()
{
    rm -rf doc
    mkdir -p doc
    cd doc
    DOC_MODULE=khovsgol
    echo "scan"
    gtkdoc-scan \
        --module=$DOC_MODULE \
        --source-dir=../c
    echo "scanobj"
    gtkdoc-scangobj \
        --module=$DOC_MODULE
    echo "mkdb"
    gtkdoc-mkdb \
        --module=$DOC_MODULE \
        --source-dir=../c \
        --output-format=xml
    mkdir -p html
    cd html
    echo "mkhtml"
    gtkdoc-mkhtml \
        $DOC_MODULE \
        ../$DOC_MODULE-docs.xml
    cd ..
    echo "fixxref"
    gtkdoc-fixxref \
        --module=$DOC_MODULE \
        --module-dir=html
}

vdoc()
{
    rm -rf doc\
    valadoc \
        --basedir=src \
        --directory=doc \
        --vapidir=/usr/share/vala-0.18/vapi \
        \
        --pkg=libsoup-2.4 \
        --pkg=gee-1.0 \
        --pkg=json-glib-1.0 \
        --pkg=posix \
        --pkg=sqlite3 \
        --pkg=gtk+-3.0 \
        --pkg=libdaemon
}

ROOT=$(cd "${0%/*}" 2>/dev/null; echo "$PWD")
cd "$ROOT"

#compile khovsgold src/server src/lib
compile khovsgolc src/cli src/client src/lib
#compile khovsgol src/gui src/client src/lib

#ccode src/server src/lib
#doc
