#!/bin/bash

# apt-get install valac-0.18 gtk-doc-tools

# Gee:          apt-get install libgee-dev            valac --pkg=gee-1.0
# Soup:         apt-get install libsoup2.4-dev        valac --pkg=libsoup-2.4
# Json:         apt-get install libjson-glib-dev      valac --pkg=json-glib-1.0
# Sqlite:       apt-get install libsqlite3-dev        valac --pkg=sqlite3
# Posix:                                              valac --pkg=posix --Xcc=-D_GNU_SOURCE
# Gtk:          apt-get install libgtk-3-dev          valac --pkg=gtk+-3.0
# Daemon:       apt-get install libdaemon-dev         valac --pkg=libdaemon
# Gst:          apt-get install libgstreamer1.0-dev   valac --pkg=gstreamer-1.0
# Unity:        apt-get install libunity-dev          valac --pkg=unity
# Indicate:     apt-get install libindicate-dev       valac --pkg=Indicate-0.7 --Xcc=-I/usr/include/libindicate-0.7 --Xcc=-lindicate
# TagLib:       apt-get install libtagc0-dev          valac --pkg=taglib_c
# AppIndicator: apt-get install libappindicator-dev   valac --pkg=appindicator-0.1
# Avahi:        apt-get install libavahi-gobject-dev  valac --pkg=avahi-gobject

# gstreamer1.0-pulseaudio, gstreamer1.0-plugins-base

compile()
{
    find "${@:2}" \( -name '*.gs' -o -name '*.vala' \) -print0 | xargs -r0 \
    valac \
        --basedir=src \
        --output=$1 \
        --directory=bin \
        \
        --thread \
        --target-glib=2.32 \
        --Xcc=-w \
        --debug \
        \
        --pkg=libsoup-2.4 \
        --pkg=gee-1.0 \
        --pkg=json-glib-1.0 \
        --pkg=posix --Xcc=-D_GNU_SOURCE \
        --pkg=sqlite3 \
        --pkg=gtk+-3.0 \
        --pkg=libdaemon \
        --pkg=gstreamer-1.0 \
        --pkg=unity \
        --pkg=Indicate-0.7 --Xcc=-I/usr/include/libindicate-0.7 --Xcc=-lindicate \
        --pkg=taglib_c \
        --pkg=avahi-gobject

        #--enable-deprecated \
}

ccode()
{
    rm -rf c
    find "${@:2}" \( -name '*.gs' -o -name '*.vala' \) -print0 | xargs -r0 \
    valac \
        --ccode \
        --basedir=src \
        --directory=c \
        --header=c/khovsgol.h \
        \
        --thread \
        --target-glib=2.32 \
        --Xcc=-w \
        \
        --pkg=libsoup-2.4 \
        --pkg=gee-1.0 \
        --pkg=json-glib-1.0 \
        --pkg=posix --Xcc=-D_GNU_SOURCE \
        --pkg=sqlite3 \
        --pkg=gtk+-3.0 \
        --pkg=libdaemon \
        --pkg=gstreamer-1.0 \
        --pkg=unity \
        --pkg=Indicate-0.7 \
        --pkg=taglib_c \
        --pkg=avahi-gobject
}

doc()
{
    rm -rf doc
    mkdir -p doc
    cd doc
    DOC_MODULE=khovsgol
    echo "scan"
    gtkdoc-scan \
        --module=$DOC_MODULE \
        --source-dir=../c
    echo "scanobj"
    gtkdoc-scangobj \
        --module=$DOC_MODULE
    echo "mkdb"
    gtkdoc-mkdb \
        --module=$DOC_MODULE \
        --source-dir=../c \
        --output-format=xml
    mkdir -p html
    cd html
    echo "mkhtml"
    gtkdoc-mkhtml \
        $DOC_MODULE \
        ../$DOC_MODULE-docs.xml
    cd ..
    echo "fixxref"
    gtkdoc-fixxref \
        --module=$DOC_MODULE \
        --module-dir=html
}

vdoc()
{
    rm -rf doc\
    valadoc \
        --basedir=src \
        --directory=doc \
        --vapidir=/usr/share/vala-0.18/vapi \
        \
        --pkg=libsoup-2.4 \
        --pkg=gee-1.0 \
        --pkg=json-glib-1.0 \
        --pkg=posix \
        --pkg=sqlite3 \
        --pkg=gtk+-3.0 \
        --pkg=libdaemon
}

ROOT=$(cd "${0%/*}" 2>/dev/null; echo "$PWD")
cd "$ROOT"

# Desktop file and icon for our user
sed "s|/usr/bin/|$ROOT/bin/|g" "$ROOT/resources/khovsgol.desktop" > ~/.local/share/applications/khovsgol.desktop
cp "$ROOT/resources/khovsgol.svg" ~/.local/share/icons/

#compile khovsgold src/models.gs src/iterators.gs src/server src/lib
compile khovsgolc src/models.gs src/iterators.gs src/client/api.gs src/client/utilities.gs src/client/cli src/lib/logging src/lib/console src/lib/nap src/lib/json src/lib/avahi
#compile khovsgol src/models.gs src/iterators.gs src/client/client.gs src/client/utilities.gs src/client/configuration.gs src/client/api.gs src/client/plugins src/client/gtk src/lib/logging src/lib/console src/lib/nap src/lib/json src/lib/dbus src/lib/gtk src/lib/avahi

#ccode src/server src/lib
#doc

# Useful run options:
#  G_DEBUG=fatal_warnings
#  GST_DEBUG=1
